### ISSUE TITLE
Removal of Stages in groovy does not remove stages in bamboo

### ISSUE THREAD

**Issue by jdonofrio728** [mibexsoftware/bamboo-plan-dsl-plugin#10]
It seems that if we remove a stage, and check in the change to the seed repository, the stage is not deleted from bamboo. The same applies with jobs.

**Comment by mrueegg** [comment]
This is correct, we currently do not delete plans, jobs, stages and deployment projects if they are not in the DSL script (anymore). I think before we can do this, we need to make this explicit to the user with a configurable option, something like this:

"Action for removed entities":

- Ignore
- Disable
- Delete

where _Ignore_ should probably be the default. What do you think?

**Comment by jdonofrio728** [comment]
I talked with some of my colleagues about this, and we are of the opinion that the codebase should never be able to have a different state than what is deployed to bamboo. You can have it configurable, however it makes it so that by default your code and service could diverge.

So I'm more of the opinion that it should at least default to delete if you want it configurable. I appreciate you asking for my input :)

**Comment by mrueegg** [comment]
We discussed this internally and basically agree with you. We will consider this for the next release of the plug-in. 

The only question is how far we should go with this. E.g., would you also delete a plan if it is not mentioned anymore in the DSL? Let's say you have to plans `P1` and `P2` in project `P`, and your DSL looks like this:

```groovy
project('P') {
  plan('p1') {
  }
}
```

When you run you seed task with this DSL, would you then expect that plan `p2` gets deleted?

**Comment by grdl** [comment]
We're also looking forward to have this feature implemented. I'd expect that if I remove a task, job or stage definition from DSL they should also be removed from Bamboo. However, it should **not** be possible to remove plans and projects via DSL (without an explicit setting). 

Reason is - removed tasks, jobs or stages can be easily recreated (from previous revision of DSL or manually) and the impact of such change is low. However, if you remove a project or plan you also lose all build history, logs and artifacts!

Implementing it the way I suggest will protect users from accidentaly deleting plans and still enable them to have plans fully configurable via DSL.

**Comment by mrueegg** [comment]
@grdl Thanks for your feedback. I agree with your points. We will try to provide this feature with the next release of the plug-in.

**Comment by jdonofrio728** [comment]
Hey I also agree that its probably best to not remove the plans or projects unless you specifically say so. Thanks!

**Comment by mrueegg** [comment]
Hi all,

Just wanted to let you know that I'm making progress with this feature request and that we will soon ship this. 

One open question though is how we should handle environments in deployment projects. It is a bit similar to plans I think where when you delete them you will also lose artifacts and logs. So what do you think? Should we remove existing environments not contained in the DSL scripts or better be consistent with the way we handle plans and leave them untouched when not referenced?

**Comment by jdonofrio728** [comment]
I'll run this by my team and report back on Monday.

**Comment by grdl** [comment]
I think deployment projects and environments should be handled in a similar way as projects and plans - don't remove them. The chance of loosing all your deployment history and logs is too big.

Meanwhile I'd like to point out that also other elements (not only jobs and stages) are not removed from Bamboo when removed from DSL:
* repositories
* triggers
* variables
* artifact definitions

Interestingly, dependencies and notifications do disappear from Bamboo when I remove them from DSL.

**Comment by mrueegg** [comment]
@grdl I think you are right, we should handle deployment projects and environments the same as projects and plans.

Concerning the other entities currently being not removed: this is correct, the plug-in behavior is not consistent yet. We will make sure that all elements are in-sync with the DSL (apart from projects, plans and environments) with the next release. 

Is anybody interested to beta-test this before I'll ship it to the Marketplace?

**Comment by grdl** [comment]
Great! Looking forward to the next release. Thanks for your quick replies and for the plugin itself. We're still evaluating it but it seems very promising and looks like it will make a lot of our Bamboo problems go away :)
I'll be happy to beta-test next release. I'll contact you via email to arrange it.

**Comment by hsmade** [comment]
I'm happy to beta test as well. I'm build a python script to auto-generate the DSL based on the environments for which our pipeline needs to build. I could really make use of this feature and am currently in development phase still.

**Comment by mrueegg** [comment]
Hi @grdl @hsmade,

Thanks for your offer. Could you please write an email to support@mibexsoftware.com? This will create a service desk ticket where we can attach a SNAPSHOT of the plug-in.

**Comment by mrueegg** [comment]
Fixed with release 1.5.0. Thanks for bringing this up!
