### ISSUE TITLE
artifact location not working

### ISSUE THREAD

**Issue by hsmade** [mibexsoftware/bamboo-plan-dsl-plugin#11]
Given the following groovy snippet:
				artifacts {
					definition(name: 'Database', copyPattern: '*.sqlite') {
						location: 'database/main'
						shared: true
					}
				}

The result is that the location is 'null'. Where as when I check for a manual set artifact, using the 'Plan DSL', I do see a text value there with the text I set. Am I doing something wrong?

**Comment by hsmade** [comment]
To answer myself: yes. The correct structure is this:
artifacts {
definition(name: 'Database', copyPattern: '*.sqlite') {
location 'database/main'
shared true
}
}

**Comment by mrueegg** [comment]
Hi,

Thanks for your feedback. You're right, the syntax in the first example just defines a label with the name `location`, but this does not call the method `location` with the passed value, hence it is ignored and `location` is null.

Unfortunately, I think we cannot do much on the library-side to prevent errors/typos like this. But I will definitely take this up into our FAQ section.
