### ISSUE TITLE
Generated DSL in "Plan DSL" tab is incorrect

### ISSUE THREAD

**Issue by grdl** [mibexsoftware/bamboo-plan-dsl-plugin#12]
Several elements of generated DSL in "Plan DSL" tab are incorrect:
* Plans and jobs are disabled (have `enabled: false` element) even though they are enabled
* Multiline strings in script tasks are wrapped in single quotes intead of triple quotes (`'''`)
* There are no elements for triggers, notifications, variables and dependencies even though all of them are defined
* `scm` element is empty even though repositories are defined

**Comment by mrueegg** [comment]
Hi,

I can confirm the first two issues. We will fix them with the next release of the plug-in. 

Note that we do not support all existing elements for the experimental "DSL generation" feature. Triggers, notifications, variables, dependencies and repositories are not yet supported. We try to address as many of the missing elements as possible for the next release.

**Comment by mrueegg** [comment]
Fixed with release 1.5.0. Thanks for bringing this up!
