### ISSUE TITLE
advancedOptions do not work for bitbucketServer scm

### ISSUE THREAD

**Issue by grdl** [mibexsoftware/bamboo-plan-dsl-plugin#13]
When you create a repository using `bitbucketServer ` scm the advanced options are not populated as defined in DSL. Also, `enableRepositoryCachingOnRemoteAgents` option is not available there.

This is most probably because `ScmBitbucketServer.groovy` uses
`private AdvancedGitRepoOptions advancedOptions`
instead of
`private AdvancedGitOptions advancedOptions`

**Comment by mrueegg** [comment]
You're right. We will fix this for the next release of the plug-in.

**Comment by mrueegg** [comment]
Fixed with release 1.5.0. Thanks for bringing this up!
