### ISSUE TITLE
releaseversioning seems not to work

### ISSUE THREAD

**Issue by hsmade** [mibexsoftware/bamboo-plan-dsl-plugin#14]
bamboo: 5.12.4 build 51217
plugin: 1.4.1

Following the example from bamboo-plan-dsl-plugin/src/test/resources/dsls/deployprojs/DeploymentProject.groovy I tried the DSL:

        project("TEST") {
            name "TEST"

            plan("TESTDEPLOY") {
                name "test deploy versioning"

                deploymentProject("dp1") {
                    description "desc1"
                    useCustomPlanBranch "develop"

                    environment("env1") {
                        description "desc"
                    }

                    releaseVersioning(nextReleaseVersion: '1.0-m1') {
                        autoIncrement()
                        variables "test1", "test2"
                    }
                }
            }
        }

and got:

        simple	31-Jan-2017 13:55:53	Starting task 'seed' of type 'ch.mibex.bamboo.plandsl:seed.task'
        simple	31-Jan-2017 13:55:53	Plan DSL for Bamboo: start processing...
        simple	31-Jan-2017 13:55:53	Plan DSL for Bamboo: will now process inline script: project("TEST") {     name "TEST"      plan("TESTDEPLOY") {         name "test d...
        simple	31-Jan-2017 13:55:53	Plan DSL for Bamboo: Warning: (script:2): name is deprecated
        simple	31-Jan-2017 13:55:53	Plan DSL for Bamboo: Warning: (script:4): plan is deprecated
        simple	31-Jan-2017 13:55:53	Plan DSL for Bamboo: Warning: (script:5): name is deprecated
        error	31-Jan-2017 13:55:53	Error occurred while running Task 'seed(1)' of type ch.mibex.bamboo.plandsl:seed.task.
        error	31-Jan-2017 13:55:53	java.lang.IllegalArgumentException: Could not parse key 'null'
        error	31-Jan-2017 13:55:53		at com.atlassian.bamboo.plan.PlanKeys.getPlanKey(PlanKeys.java:320)
        error	31-Jan-2017 13:55:53		at com.atlassian.bamboo.plan.PlanKeys$getPlanKey$1.call(Unknown Source)
        error	31-Jan-2017 13:55:53		at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        error	31-Jan-2017 13:55:53		at com.atlassian.bamboo.plan.PlanKeys$getPlanKey$1.call(Unknown Source)
        error	31-Jan-2017 13:55:53		at ch.mibex.bamboo.plandsl.plugin.services.DeploymentProjectService.determineRelatedPlanBranchKey(DeploymentProjectService.groovy:41)
        error	31-Jan-2017 13:55:53		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        error	31-Jan-2017 13:55:53		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        error	31-Jan-2017 13:55:53		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        error	31-Jan-2017 13:55:53		at java.lang.reflect.Method.invoke(Method.java:483)
        error	31-Jan-2017 13:55:53		at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        error	31-Jan-2017 13:55:53		at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        error	31-Jan-2017 13:55:53		at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:384)
        error	31-Jan-2017 13:55:53		at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1021)
        error	31-Jan-2017 13:55:53		at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69)
        error	31-Jan-2017 13:55:53		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
        error	31-Jan-2017 13:55:53		at ch.mibex.bamboo.plandsl.plugin.services.DeploymentProjectService$_createOrUpdate_closure1$_closure11$_closure12.doCall(DeploymentProjectService.groovy:28)
        error	31-Jan-2017 13:55:53		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        error	31-Jan-2017 13:55:53		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        error	31-Jan-2017 13:55:53		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        error	31-Jan-2017 13:55:53		at java.lang.reflect.Method.invoke(Method.java:483)
        error	31-Jan-2017 13:55:53		at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        error	31-Jan-2017 13:55:53		at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        error	31-Jan-2017 13:55:53		at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
        error	31-Jan-2017 13:55:53		at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1021)
        error	31-Jan-2017 13:55:53		at groovy.lang.Closure.call(Closure.java:426)
        error	31-Jan-2017 13:55:53		at groovy.lang.Closure.call(Closure.java:442)
        error	31-Jan-2017 13:55:53		at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2030)
        error	31-Jan-2017 13:55:53		at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2015)
        error	31-Jan-2017 13:55:53		at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2056)
        error	31-Jan-2017 13:55:53		at org.codehaus.groovy.runtime.dgm$162.invoke(Unknown Source)
        error	31-Jan-2017 13:55:53		at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
        error	31-Jan-2017 13:55:53		at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
        error	31-Jan-2017 13:55:53		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        error	31-Jan-2017 13:55:53		at ch.mibex.bamboo.plandsl.plugin.services.DeploymentProjectService$_createOrUpdate_closure1$_closure11.doCall(DeploymentProjectService.groovy:24)
        error	31-Jan-2017 13:55:53		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        error	31-Jan-2017 13:55:53		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        error	31-Jan-2017 13:55:53		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        error	31-Jan-2017 13:55:53		at java.lang.reflect.Method.invoke(Method.java:483)
        error	31-Jan-2017 13:55:53		at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        error	31-Jan-2017 13:55:53		at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        error	31-Jan-2017 13:55:53		at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
        error	31-Jan-2017 13:55:53		at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1021)
        error	31-Jan-2017 13:55:53		at groovy.lang.Closure.call(Closure.java:426)
        error	31-Jan-2017 13:55:53		at groovy.lang.Closure.call(Closure.java:442)
        error	31-Jan-2017 13:55:53		at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2030)
        error	31-Jan-2017 13:55:53		at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2015)
        error	31-Jan-2017 13:55:53		at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2056)
        error	31-Jan-2017 13:55:53		at org.codehaus.groovy.runtime.dgm$162.invoke(Unknown Source)
        error	31-Jan-2017 13:55:53		at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
        error	31-Jan-2017 13:55:53		at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
        error	31-Jan-2017 13:55:53		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        error	31-Jan-2017 13:55:53		at ch.mibex.bamboo.plandsl.plugin.services.DeploymentProjectService$_createOrUpdate_closure1.doCall(DeploymentProjectService.groovy:23)
        error	31-Jan-2017 13:55:53		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        error	31-Jan-2017 13:55:53		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        error	31-Jan-2017 13:55:53		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        error	31-Jan-2017 13:55:53		at java.lang.reflect.Method.invoke(Method.java:483)
        error	31-Jan-2017 13:55:53		at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        error	31-Jan-2017 13:55:53		at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        error	31-Jan-2017 13:55:53		at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
        error	31-Jan-2017 13:55:53		at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1021)
        error	31-Jan-2017 13:55:53		at groovy.lang.Closure.call(Closure.java:426)
        error	31-Jan-2017 13:55:53		at groovy.lang.Closure.call(Closure.java:442)
        error	31-Jan-2017 13:55:53		at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2030)
        error	31-Jan-2017 13:55:53		at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2015)
        error	31-Jan-2017 13:55:53		at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2056)
        error	31-Jan-2017 13:55:53		at org.codehaus.groovy.runtime.dgm$162.invoke(Unknown Source)
        error	31-Jan-2017 13:55:53		at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
        error	31-Jan-2017 13:55:53		at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
        error	31-Jan-2017 13:55:53		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        error	31-Jan-2017 13:55:53		at ch.mibex.bamboo.plandsl.plugin.services.DeploymentProjectService.createOrUpdate(DeploymentProjectService.groovy:22)
        error	31-Jan-2017 13:55:53		at ch.mibex.bamboo.plandsl.plugin.services.DeploymentProjectService$createOrUpdate.call(Unknown Source)
        error	31-Jan-2017 13:55:53		at ch.mibex.bamboo.plandsl.plugin.PlanDslExecutorImpl.execute(PlanDslExecutorImpl.groovy:66)
        error	31-Jan-2017 13:55:53		at ch.mibex.bamboo.plandsl.plugin.PlanDslExecutor$execute.call(Unknown Source)
        error	31-Jan-2017 13:55:53		at ch.mibex.bamboo.plandsl.plugin.task.SeedTask$_execute_closure2$_closure3.doCall(SeedTask.groovy:98)
        error	31-Jan-2017 13:55:53		at ch.mibex.bamboo.plandsl.plugin.task.SeedTask$_execute_closure2$_closure3.doCall(SeedTask.groovy)
        error	31-Jan-2017 13:55:53		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        error	31-Jan-2017 13:55:53		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        error	31-Jan-2017 13:55:53		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        error	31-Jan-2017 13:55:53		at java.lang.reflect.Method.invoke(Method.java:483)
        error	31-Jan-2017 13:55:53		at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        error	31-Jan-2017 13:55:53		at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        error	31-Jan-2017 13:55:53		at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
        error	31-Jan-2017 13:55:53		at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1021)
        error	31-Jan-2017 13:55:53		at groovy.lang.Closure.call(Closure.java:426)
        error	31-Jan-2017 13:55:53		at groovy.lang.Closure.call(Closure.java:420)
        error	31-Jan-2017 13:55:53		at com.atlassian.bamboo.utils.BambooRunnables$BambooRunnableFromCallable.run(BambooRunnables.java:71)
        error	31-Jan-2017 13:55:53		at com.atlassian.bamboo.security.ImpersonationHelper.runWith(ImpersonationHelper.java:31)
        error	31-Jan-2017 13:55:53		at com.atlassian.bamboo.applinks.ImpersonationServiceImpl$1.call(ImpersonationServiceImpl.java:85)
        error	31-Jan-2017 13:55:53		at java_util_concurrent_Callable$call.call(Unknown Source)
        error	31-Jan-2017 13:55:53		at ch.mibex.bamboo.plandsl.plugin.task.SeedTask$_execute_closure2.doCall(SeedTask.groovy:100)
        error	31-Jan-2017 13:55:53		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        error	31-Jan-2017 13:55:53		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        error	31-Jan-2017 13:55:53		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        error	31-Jan-2017 13:55:53		at java.lang.reflect.Method.invoke(Method.java:483)
        error	31-Jan-2017 13:55:53		at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        error	31-Jan-2017 13:55:53		at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        error	31-Jan-2017 13:55:53		at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
        error	31-Jan-2017 13:55:53		at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1021)
        error	31-Jan-2017 13:55:53		at groovy.lang.Closure.call(Closure.java:426)
        error	31-Jan-2017 13:55:53		at groovy.lang.Closure.call(Closure.java:442)
        error	31-Jan-2017 13:55:53		at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2030)
        error	31-Jan-2017 13:55:53		at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2015)
        error	31-Jan-2017 13:55:53		at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2068)
        error	31-Jan-2017 13:55:53		at org.codehaus.groovy.runtime.dgm$164.invoke(Unknown Source)
        error	31-Jan-2017 13:55:53		at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
        error	31-Jan-2017 13:55:53		at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
        error	31-Jan-2017 13:55:53		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        error	31-Jan-2017 13:55:53		at ch.mibex.bamboo.plandsl.plugin.task.SeedTask.execute(SeedTask.groovy:94)
        error	31-Jan-2017 13:55:53		at com.atlassian.bamboo.task.TaskExecutorImpl.lambda$executeTasks$271(TaskExecutorImpl.java:313)
        error	31-Jan-2017 13:55:53		at com.atlassian.bamboo.task.TaskExecutorImpl$$Lambda$410/589179073.call(Unknown Source)
        error	31-Jan-2017 13:55:53		at com.atlassian.bamboo.task.TaskExecutorImpl.executeTaskWithPrePostActions(TaskExecutorImpl.java:246)
        error	31-Jan-2017 13:55:53		at com.atlassian.bamboo.task.TaskExecutorImpl.executeTasks(TaskExecutorImpl.java:313)
        error	31-Jan-2017 13:55:53		at com.atlassian.bamboo.task.TaskExecutorImpl.execute(TaskExecutorImpl.java:118)
        error	31-Jan-2017 13:55:53		at com.atlassian.bamboo.build.pipeline.tasks.ExecuteBuildTask.call(ExecuteBuildTask.java:74)
        error	31-Jan-2017 13:55:53		at com.atlassian.bamboo.v2.build.agent.DefaultBuildAgent.build(DefaultBuildAgent.java:215)
        error	31-Jan-2017 13:55:53		at com.atlassian.bamboo.v2.build.agent.BuildAgentControllerImpl$1.call(BuildAgentControllerImpl.java:139)
        error	31-Jan-2017 13:55:53		at com.atlassian.bamboo.v2.build.agent.BuildAgentControllerImpl$1.call(BuildAgentControllerImpl.java:130)
        error	31-Jan-2017 13:55:53		at com.atlassian.bamboo.variable.CustomVariableContextImpl.withVariableSubstitutor(CustomVariableContextImpl.java:221)
        error	31-Jan-2017 13:55:53		at com.atlassian.bamboo.v2.build.agent.BuildAgentControllerImpl.waitAndPerformBuild(BuildAgentControllerImpl.java:129)
        error	31-Jan-2017 13:55:53		at com.atlassian.bamboo.v2.build.agent.DefaultBuildAgent$1.run(DefaultBuildAgent.java:137)
        error	31-Jan-2017 13:55:53		at com.atlassian.bamboo.utils.BambooRunnables$1.run(BambooRunnables.java:51)
        error	31-Jan-2017 13:55:53		at com.atlassian.bamboo.security.ImpersonationHelper.runWith(ImpersonationHelper.java:31)
        error	31-Jan-2017 13:55:53		at com.atlassian.bamboo.security.ImpersonationHelper.runWithSystemAuthority(ImpersonationHelper.java:20)
        error	31-Jan-2017 13:55:53		at com.atlassian.bamboo.security.ImpersonationHelper$1.run(ImpersonationHelper.java:52)
        error	31-Jan-2017 13:55:53		at java.lang.Thread.run(Thread.java:744)

**Comment by hsmade** [comment]
What does seem to work is:

        project("TEST") {
            name "TEST"

            plan("TESTDEPLOY") {
                name "test deploy versioning"

                deploymentProject("dp1") {
                    description "desc1"

                    environment("env1") {
                        description "desc"
                    }
                    releaseVersioning('unit-xxxx-${bamboo.semver.version}') {
                        autoIncrement false
                        variables "test1"
                    }    
                }
            }
        }

The variables needs to be there though. If I remove that line, it breaks with the same stacktrace.

**Comment by mrueegg** [comment]
Hi,

Thanks for your feedback. Does the plan `TESTDEPLOY` have a plan branch `develop`? I guess not. The next release will have an improved error handling which will give you a hint if the plan branch is missing but referenced from a deployment project.

**Comment by hsmade** [comment]
I agree that might be a problem in the first snippet. But take a look at the second. This works fine, until I remove the 'variables "test1"'. Then I get the same error.
So I think this might be a bug with the bamboo api itself, but it could be handled or maybe even circumvented by the plugin in a better way.

**Comment by mrueegg** [comment]
@hsmade I was able to reproduce this as well. Will be fixed with the new release today.
