### ISSUE TITLE
Some variables don't get set

### ISSUE THREAD

**Issue by OlympusMonds** [mibexsoftware/bamboo-plan-dsl-plugin#21]
Hello - first of all, great plugin, amazing!

I'm having some issues with some variables not being filled. For example:

```
        dependencies {
            blockingStrategy DependencyBlockingStrategy.BLOCK_BUILD_IF_PARENT_PLANS_HAVE_UNBUILT_CHANGES
            childPlans "TUT-CL", "SEL4BENCH-MAINLINE"
        }
```

```
        notifications {
            hipchat(event: NotificationEvent.ALL_JOBS_COMPLETED,
                    apiToken: '<my token>',
                    room: '<my room>') {
                notifyParticipants false
            }
            hipchat(event: NotificationEvent.JOB_HUNG,
                    apiToken: '<my token>',
                    room: '<my room>') {
                notifyParticipants false
            }
        }
```

When I run the DSL task, everything gets filled out in Bamboo, except for:

- on my hipchat notifications, notify is set to true (despite me saying 'false')
- The dependency blocking strategy has nothing selected (despite me picking an enum value)

Any ideas?

**Comment by mrueegg** [comment]
Thanks for your feedback and your nice words about the plug-in :-)

We've fixed these bugs and released a new version 1.5.5. By the way, if you like our add-on, it would be awesome if you could write a short review on our Atlassian Marketplace listing about your experiences: 
https://marketplace.atlassian.com/plugins/ch.mibex.bamboo.plandsl/server/reviews

**Comment by OlympusMonds** [comment]
I'll give it a go at let you know.
Did you find any issue with the dependency strategy setting?

**Comment by mrueegg** [comment]
Yes, the blocking strategy was not set only when no advancedOptions were configured. We fixed that now.

**Comment by OlympusMonds** [comment]
Tested both, working great!

**Comment by mrueegg** [comment]
Awesome, thanks :-)
