### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by cattz** [mibexsoftware/bamboo-plan-dsl-plugin#22]
I can see some deprecation warnings in my logs:

```
02-Mar-2017 17:58:31	Plan DSL: warning: (test.groovy:80): scheduled is deprecated
02-Mar-2017 17:58:31	Plan DSL: warning: (test.groovy:113): script is deprecated
02-Mar-2017 17:58:31	Plan DSL: warning: (test.groovy:129): copyPattern is deprecated
```
but after searching your WiKi, I can not find any references to right syntax to be used.

**Comment by mrueegg** [comment]
Hi,

I documented these deprecations in the [migration guide](https://github.com/mibexsoftware/bamboo-plan-dsl-plugin/wiki/Migration) in the wiki now. I will also provide better deprecation notices in the JavaDoc of the DSL for the next release of the plug-in. Hope this helps.

**Comment by cattz** [comment]
Yes, that helps, thanks
