### ISSUE TITLE
Feature request: Requirements on deployment plans

### ISSUE THREAD

**Issue by tiagolo** [mibexsoftware/bamboo-plan-dsl-plugin#25]
Hello @mrueegg,
Could you add the option to additional requirements for deployment plans, just like it's possible to do for build plans?

**Comment by mrueegg** [comment]
Hi @tiagolo 

Could you please specify which additional requirements you mean? A screen shot of the Bamboo UI would help much.

**Comment by mrueegg** [comment]
Hi @sohrab- 

Thanks for the clarification. This is currently not possible with the latest version 1.7.2. But we have scheduled support for agent assignments for the next release 1.8.0 of the plug-in coming very soon.

Best regards,
Michael

**Comment by sohrab-** [comment]
@mrueegg, I'm looking at 1.8.0 but not seeing the agent assignment. Am I missing something here?

For anyone else facing the same problem, my current _hack_ is to create a fake executable, say `echo`, assign it to the agents I need and use it in any environment task list.

**Comment by mrueegg** [comment]
@sohrab- No, agent assignment is not part of 1.8.0. I currently work on this. Hope to release it very soon with the next release. Thanks for the tip with the workaround :-)

**Comment by mrueegg** [comment]
Implemented with 1.9.0. For the expected syntax, please see the API documentation: https://mibexsoftware.github.io/bamboo-plan-dsl-plugin/#agent_assignments. Thanks for bringing this up!
