### ISSUE TITLE
Extra colons in generated DSL artifact objects

### ISSUE THREAD

**Issue by paulojblack** [mibexsoftware/bamboo-plan-dsl-plugin#26]
Edit
--
I just saw under the FAQ in the wiki you highlighted the colon issue using artifact as an example so I assume this is not the first time it's been reported. I don't know if the fact that the generator outputs the keys like this has been reported so I'll leave the issue open, but if this is redundant sorry for the false flag!

Hey guys - love the product, got the trial today and I'll definitely be purchasing through work, I don't know how anybody can use Bamboo for enterprise without this feature.

I did notice that I was unable to get the "share" toggle for artifacts working while playing with DSL generated from an existing plan. The cause was superfluous colons generated in the object's keys, the removal of which got me up and running again. All the other plans I looked at had the same issue.

Eg:
```
 definition(name: 'Coverage Report (System)', copyPattern: 'coverage-clover-report.xml') {
                        location: ''
                        shared: false
                    } 
```

I would love to open a PR, but from poking around it looks as though you have not open sourced the generator, is this correct? If I'm mistaken, please point me in the right direction, I've been wanting to play with Groovy for a while.

**Comment by mrueegg** [comment]
Hi @paulojblack 

Thanks for your decent feedback, much appreciated! You're right, this is a bug. I'll release a new version today with this being fixed and report back here once it is available in the Marketplace.

**Comment by mrueegg** [comment]
@paulojblack Fixed and shipped :-) Thanks again for reporting this!
