### ISSUE TITLE
How to I use the source code for the dsl provided

### ISSUE THREAD

**Issue by roerrr** [mibexsoftware/bamboo-plan-dsl-plugin#28]
I want to use the bamboo plan dsl plugin. I cloned the project into my local repo but It only contains the source for the plan DSL. How to I write my plan using the source code that was provided.

**Comment by mrueegg** [comment]
Hi. 

As a starting point I suggest that you clone the example repository at https://github.com/mibexsoftware/bamboo-plan-dsl-example. From this, you can either manually write the DSL for your plans by using the documentation from our Wiki at https://github.com/mibexsoftware/bamboo-plan-dsl-plugin/wiki or you can use the export feature of the plug-in for existing plans (still in beta phase) to get started. 

Please let me know if you have further questions. We're glad to help!
