### ISSUE TITLE
Bitbucket Server - Authentication?

### ISSUE THREAD

**Issue by muchino** [mibexsoftware/bamboo-plan-dsl-plugin#30]
Hi 

I really like your add-on but I have one issue where I can't find the resolution for. 

My config is:
![image](https://cloud.githubusercontent.com/assets/1260981/26265583/f874879a-3ce1-11e7-80de-56c1aa320c6a.png)

And I receive this issue:
                        
19-May-2017 22:21:16	Plan DSL: task failed: Bitbucket server repository authentication errors: fatal: Authentication failed for 'https://git.bitvoodoo.ch/scm/BV/advanced-chart-plugin.git/'

How can I provide my credentials? I configured an Applink with the same name.

**Comment by mrueegg** [comment]
Hi Oli,

Thanks for your feedback.

When using Bitbucket Server as an SCM configuration, there is no need to provide credentials. The communication and authentication is performed through the application link settings (probably OAuth).

When you have run the DSL task for the first time with the Bitbucket Server configuration, did you receive a message saying


    Bitbucket Server credentials required. Follow this URL in your browser and try again: http://...

?

If yes, have you followed this URL in your browser?

Best regards,
Michael

**Comment by muchino** [comment]
Hi Michael 

The URL is correct, I changed it now to the ssh url and it seems to work this way :) 

Thank you

**Comment by mrueegg** [comment]
Perfect, that's good news. Thanks for your feedback. 👍
