### ISSUE TITLE
createPlanBranchesForNewPullRequests seems to throw error in Bamboo 6 

### ISSUE THREAD

**Issue by muchino** [mibexsoftware/bamboo-plan-dsl-plugin#31]
Hi

At the moment I get an error for the call of _createPlanBranchesForNewPullRequests()_ If I replace it with _createPlanBranchesForAllNewBranches()_ everything is fine. Maybe there is a bug?
I attached the log file.

Cheers
Oli

[SANDBOX-PLANDSL-JOB1-53.log.txt](https://github.com/mibexsoftware/bamboo-plan-dsl-plugin/files/1017271/SANDBOX-PLANDSL-JOB1-53.log.txt)

**Comment by mrueegg** [comment]
Hi Oli,

thanks for your feedback. Which Bamboo version are you using?

Best regards,
Michael

**Comment by muchino** [comment]
Bamboo  6.0.0 build 60001 - 24 Apr 17

**Comment by mrueegg** [comment]
Bug confirmed in Bamboo 6.0. We will ship a bug fix very soon (next 12 hours). I'll ping back here once it is available in the Marketplace. Thanks for reporting!

**Comment by mrueegg** [comment]
Fixed with release 1.7.2. Thanks again for reporting!

**Comment by muchino** [comment]
Awesome :)
