### ISSUE TITLE
error in deployment project with such a definition

### ISSUE THREAD

**Issue by muchino** [mibexsoftware/bamboo-plan-dsl-plugin#37]
releaseVersioning(nextReleaseVersion: '${bamboo.' + 'maven.version}') {
                    autoIncrement()
                    variables 'maven.version'
                }

**Comment by muchino** [comment]
This worked:
 releaseVersioning(nextReleaseVersion: '${bamboo.maven.version}') {
                    //autoIncrement()
                    variables 'bamboo.maven.version'
                }

**Comment by mrueegg** [comment]
Thanks for your feeedback! I was trying to reproduce this as well, but with no luck:

          releaseVersioning(nextReleaseVersion: '1.0-${bamboo.buildNumber}') {
              autoIncrement()
              variables 'var1', 'var2'
          }
