### ISSUE TITLE
No Custom Notifications in Environment Notification

### ISSUE THREAD

**Issue by sohrab-** [mibexsoftware/bamboo-plan-dsl-plugin#48]
`EnvironmentNotifications` or its parent, `AbstractNotifications`,  do not expose Custom Notifications. 

This is supported by Bamboo itself. For example, custom Slack notification:

![image](https://user-images.githubusercontent.com/4444588/28512310-b70a1306-7094-11e7-8321-ca2fdd2df0af.png)

Ideally we need to push `custom()` methods from `Notifications` up to `AbstractNotifications`.

**Comment by mrueegg** [comment]
@sohrab- Thanks for bringing this up! I will fix it for the next release.

**Comment by mrueegg** [comment]
Fixed with 1.9.0. Thanks for bringing this up!
