### ISSUE TITLE
Travis build for 1.9.1 did not happen

### ISSUE THREAD

**Issue by sohrab-** [mibexsoftware/bamboo-plan-dsl-plugin#52]
Hi Michael, I can't see the latest version of the plugin on jitpack.io:

![image](https://user-images.githubusercontent.com/4444588/28762546-d51c0f46-75fa-11e7-899c-0fd547b50169.png)

Looks like the Travis build didn't happen:

![image](https://user-images.githubusercontent.com/4444588/28762567-f35c699c-75fa-11e7-843a-bb4deae0989d.png)

**Comment by mrueegg** [comment]
Thanks for the hint. You're right, but this time the changes were only part of the Atlassian plug-in, so I didn't have to update the DSL library. Normally, changes happen in both parts and I will update the versions accordingly. For 1.9.1, it will be enough if you just update your Atlassian plug-in installation in the UPM.

**Comment by sohrab-** [comment]
Ah my mistake. I thought the agent assignment stuff was in 1.9.1 but I see it's in 1.9.0. Thanks.
