### ISSUE TITLE
Cannot specify the repos to use in Bitbucket Server Trigger

### ISSUE THREAD

**Issue by sohrab-** [mibexsoftware/bamboo-plan-dsl-plugin#53]
Bitbucket Server trigger DSL does not let you pick the repositories for the trigger.

In Bamboo, you can choose the repos that the trigger applies to. This is specially useful when you have multiple repos in the plan.

![image](https://user-images.githubusercontent.com/4444588/28762659-95259848-75fb-11e7-8c74-bcd6cafc8614.png)

Ideally `ch.mibex.bamboo.plandsl.dsl.triggers.BitbucketServerTrigger` should expose a `repositories(String... repositories)` similar to some of the other triggers.

**Comment by mrueegg** [comment]
You're right. I will update the DSL accordingly for the next release. Thanks for the hint!

**Comment by sohrab-** [comment]
When can we expect the next release? Also can you think of a work-around for this, in the meanwhile so we can avoid trigger builds too often?

**Comment by mrueegg** [comment]
@sohrab- We plan to deliver the next release this week. Unfortunately, I cannot think of any workaround. I'll try my best to get the new release out ASAP :-)

**Comment by sohrab-** [comment]
Thanks, Michael.

**Comment by mrueegg** [comment]
We now support repositories on Bitbucket Server trigges with the latest release 1.9.2. Thanks again for bringing this up!

**Comment by sohrab-** [comment]
Works well. Thanks!
