### ISSUE TITLE
Feature Request: Custom miscellaneous plug in options for jobs

### ISSUE THREAD

**Issue by tiagolo** [mibexsoftware/bamboo-plan-dsl-plugin#55]
Hello @mrueegg long time no see,
could you provide us with the possibility to set custom miscellaneous options for jobs, just like it is possible to do it with [Plans Miscellaneous] (https://github.com/mibexsoftware/bamboo-plan-dsl-plugin/wiki/Miscellaneous-plug-in-options)?

**Comment by mrueegg** [comment]
Hi @tiagolo :-)

Sure, will be provided for the next release! Could you please give me an example of a plug-in that does offer custom misc options on the job level so that I can test this? That would help me much.

**Comment by tiagolo** [comment]
Sure, 
Right now I am doing some experimentations with the `Dynamic Plans, DSL & Pipeline for Bamboo` because it allows me to switch tasks at runtime, although not sure if it's the ideal configuration for my situation.

![image](https://user-images.githubusercontent.com/144190/29030964-1e165fae-7b63-11e7-96ce-f4b074030fb2.png)

**Comment by tiagolo** [comment]
PS: Let me explain a little of what are my needs, so I can share this experience.

I need to automate our release process which uses git-flow branching strategy, we already have a set of scripts that do this process for us, but each branch needs to run different instructions since bamboo would not allow us to have different jobs for different branches of the same build plan. I am experimenting with the plugin I have mentioned earlier, to see if this process will be viable in this configuration:

For example from the "develop" branch is created a "release/x.x.x" branch and configuration file like `pom.xml` are updated to a release candidate version, with "-RCx" on the version number.

Through out the process, many release candidates are created so the "release/x.x.x" need to just update the configuration files and build the new "RC" artifacts.

Once the release candidate is approved, it's time to update the configuration files once more, but with the "-RELEASE" suffix, and finally, merge the "release/x.x.x" branch to the branches "master" and "develop"

![image](https://user-images.githubusercontent.com/144190/29032069-8db21cce-7b66-11e7-88a6-4175e6f5a451.png)

I also have seen others strategies of using different build plans for release and CI, as mentioned on this post (https://community.atlassian.com/t5/Bamboo-questions/Bamboo-with-maven-and-gitflow/qaq-p/218843), but I not sure about then yet.

**Comment by mrueegg** [comment]
We now support custom misc options on job level with the latest release 1.9.2. Thanks again for bringing this up!
