### ISSUE TITLE
Feature Proposal - Job Clean working directory after each build

### ISSUE THREAD

**Issue by tiagolo** [mibexsoftware/bamboo-plan-dsl-plugin#6]
Hello @mrueegg,
Could you add the option `cleanWorkingDirectory` present on the miscellaneous tab of the Jobs?
I know it's in your plans to add the Miscellaneous in the DSL, but if you could rush this option it would be of great help already.

**Comment by mrueegg** [comment]
Hi @tiagolo 

Sure, I've just implemented all the settings of the job misc tab. The syntax looks like follows:

```groovy
                miscellaneous {
                    cleanWorkingDirectoryAfterEachBuild()

                    overrideDefaultHangingBuildDetectionCriteria {
                        buildTimeMultiplier 2.5
                        logQuietTime 10
                        buildQueueTimeout 60
                    }

                    nCoverOutputWillBeProduced {
                        nCoverXmlDirectory 'a/b/c'
                    }

                    cloverCodeCoverage {
                        automaticallyIntegrateCloverIntoBuild(cloverLicense: 'LICENSE') {
                            generateCloverHistoricalReport()
                            generateJSONReport()
                        }
                    }

                    patternMatchLabelling {
                        regexPattern '[a-z]+'
                        labels 'test'
                    }
                }
```

I'll now spin a new release and report back here when it's available in the Atlassian Marketplace.

**Comment by mrueegg** [comment]
Version 1.3.2 now available on the Marketplace ships this feature request. Could you please update and try if this works for you?

**Comment by tiagolo** [comment]
Tested, and worked fine!

**Comment by mrueegg** [comment]
Perfect, thanks for your feedback.

By the way, if you like our add-on, it would be awesome if you could write a short review on our Atlassian Marketplace listing about your experiences:

https://marketplace.atlassian.com/plugins/ch.mibex.bamboo.plandsl/server/reviews

Thanks in advance
