### ISSUE TITLE
Branch plan release versioning inheritance

### ISSUE THREAD

**Issue by sohrab-** [mibexsoftware/bamboo-plan-dsl-plugin#60]
Bamboo 6.1 provides the feature where the branch plan inherits the release versioning of the main plan.

![image](https://user-images.githubusercontent.com/4444588/29749521-5d1a224e-8b71-11e7-86fd-44b293b5a8d2.png)

Currently we cannot toggle this in the DSL.

Also even if I set them manually, next run of the Seed Plan clears the option.

**Comment by sohrab-** [comment]
The work-around I am currently looking at is to use the exposed Bamboo API, `deploymentProjectService.updateVersionNamingScheme()`, directly. 

However I am having trouble stopping Bamboo from evaluating `${bamboo.buildNumber}` too early, even when changing it to `bamboo_buildNumber`.

**Comment by mrueegg** [comment]
Fixed with release 1.9.3. Thanks for reporting it!
