### ISSUE TITLE
DSL not setting plan merge strategy

### ISSUE THREAD

**Issue by lseek** [mibexsoftware/bamboo-plan-dsl-plugin#61]
Hi,

As a follow up to: https://github.com/mibexsoftware/bamboo-plan-dsl-plugin/issues/58 - the plan branch management strategy works fine now but the other issue I raised is still not yet fixed ... the branch merging strategy is not taking effect - it remains disabled (unchecked) regardless of what I set it to in the DSL.

Can we hope for a quick fix for this?

**Comment by mrueegg** [comment]
Hi,

I'm having troubles to reproduce this bug. When I use the DSL sample from #58, the branch merging is configured correctly as far as I can see:
![github 61](https://user-images.githubusercontent.com/206944/29764140-59423fd4-8bd6-11e7-9aa3-c6fd6f0c49bf.png)
Have you used the same sample DSL?

Best regards,
Michael

**Comment by lseek** [comment]
Hi Michael,

Your screenshot looks like a Bamboo 5 ... am I correct?

The DSL was working in Bamboo 5, the problem I have is with Bamboo 6. This is what I get:
![bamboo](https://user-images.githubusercontent.com/7218840/29798114-5dd82c48-8c9e-11e7-891f-515dfb8439d4.png)

**Comment by mrueegg** [comment]
Hi @lseek 

You're right, I was testing with Bamboo 5. I was able to reproduce this problem in Bamboo 6. We will fix it for the next release coming very soon.

**Comment by mrueegg** [comment]
@lseek Fixed with release 1.9.4 :-) Thanks again for reporting it!
