### ISSUE TITLE
Polling trigger not created anymore

### ISSUE THREAD

**Issue by cosimomeli** [mibexsoftware/bamboo-plan-dsl-plugin#65]
Hi,
with the latest version of the plugin, Repository Polling triggers are no more created.
As always I see the log "Plan DSL: warning: (TriggerHelper.groovy:19): polling is deprecated" but the trigger is not created and I get no errors.
I tried with different plans and the result is the same.
All the plans have definitions for SCM, Notification and Permissions, have at least 1 stage with 1 job and a few script tasks, this are all the commons features of the plans I used.
Polling triggers worked correctly few versions ago, so this looks like a regression.

**Comment by mrueegg** [comment]
Hi @cosimomeli 

Thanks for your feedback. You are absolutely right. We've just released a bug fix release 1.9.6 which resolves this.

Best regards,
Michael
