### ISSUE TITLE
allArtifacts in deployment projects is not working correctly

### ISSUE THREAD

**Issue by tom999** [mibexsoftware/bamboo-plan-dsl-plugin#7]
If I try to define downloading all artifacts, no artifacts will be downloaded.
If I go in the Bamboo UI everything seems to be defined correctly.
Fixing is possible in Bamboo UI, if I save task again in Bamboo UI (without changing something).
Seems to me, that Bamboo UI sets the default DropDown "All artifacts" and after saving again, it's saved in the plan.

Not working configuration:
```
deploymentProject("doc_shops") {
	environment("Bamboo Server") {
		tasks {
			cleanWorkingDirectory {
			}
			artifactDownload() {
				description("Download release content")
				allArtifacts{
					destinationPath("doc")
				}
			}
			...
```

Working configuration with workaround of defining specific artifact:
```
deploymentProject("doc_shops") {
	environment("Bamboo Server") {
		tasks {
			cleanWorkingDirectory {
			}
			artifactDownload{
				description("Download release content")
				artifact("RAMLs and HTMLs"){
					destinationPath("doc")
				}
			}
			...
```

**Comment by mrueegg** [comment]
Fixed with version 1.4.0. Thanks for reporting this!
