### ISSUE TITLE
Existing notifications throw exception after plugin update

### ISSUE THREAD

**Issue by sohrab-** [mibexsoftware/bamboo-plan-dsl-plugin#76]
We have updated  the plugin to v1.9.13 (from v1.9.7 I think) and re-running the existing DSLs is causing the attached [stacktrace](https://github.com/mibexsoftware/bamboo-plan-dsl-plugin/files/1897446/stacktrace.txt).

It looks like it's trying to re-create an existing notification (a Slack notification in this case) in the deployment plan and it is hitting a database uniqueness constraint. Should it not be checking if the notification already exists and not get that far?

No changes (besides `build.gradle` version bump for the Plan DSL dependency) has been made to the scripts so the same script used work on the previous version.

Atlassian Bamboo version 6.1.1 build 60104 - 10 Aug 17

**Comment by mrueegg** [comment]
Hi @sohrab- 

Actually, we delete all notifications and re-create the ones defined in the DSL with every seed task run because there is no API to update notifications in deployment project environments.

Could you please enable "verbose logging" in the seed task, re-run it and attach the task build log output to this issue? That would help me much. Thanks!

**Comment by sohrab-** [comment]
My bad. I always run with verbose logging on. Here is the rest of that log: [full.log](https://github.com/mibexsoftware/bamboo-plan-dsl-plugin/files/1901791/full.log).

The build fails at the same place upon multiple runs.

**Comment by sohrab-** [comment]
I have confirmed reverting back to version 1.9.11 of the plugin resolves the issue. So it seems it's a regression introduced since then, most likely 1.9.12.

**Comment by mrueegg** [comment]
Hi,

We've just released a new version including a bug fix for this. Please update your plug-in installation.

Thanks again for reporting it!

Best regards,
Michael
