### ISSUE TITLE
Branch plan notifications not getting set correctly

### ISSUE THREAD

**Issue by sohrab-** [mibexsoftware/bamboo-plan-dsl-plugin#78]
I have the following in the main plan:

```groovy
notifications.custom(event: NotificationEvent.FAILED_BUILDS_AND_FIRST_SUCCESSFUL,
         pluginKey: Config.Notifications.Slack.PLUGIN_KEY) {
      configure(webhookUrl: "...")
   }
}
```

Which works fine on the main plan. I then set the following in my branch plans:

```groovy
branches {
   notifications(Branch.NotifyOnNewBranchesType.USE_PLANS_NOTIFICATION_SETTINGS)
   ...
}
```

However once the seed task runs, the branch plan's notification is not configured correctly:

![image](https://user-images.githubusercontent.com/4444588/39130869-825ce8d8-4751-11e8-8ab2-455d49bed74c.png)

I also see no logs pretaining to branch notifications in the logs: 
[plan.log](https://github.com/mibexsoftware/bamboo-plan-dsl-plugin/files/1938473/plan.log)

**Comment by mrueegg** [comment]
Hi,

Thank you for bringing this up to us.

I was able to reproduce this. Setting the notification type on individual branches works, but on the "branches" level doesn't. In your example, you actually don't set the notifications parameter on the individual branch parameter (as expected in the screen shot), so this action only affects the "branches" level.

Here's an example to reproduce the problem:

```
project(key: 'DEV', name: 'DEVOPS') {
    plan(key: 'SIMPLEPLAN', name: 'my simple plan') {
        scm {
            bitbucketCloud(name: "myBitbucketGitRepo") {
                repoSlug "project_1/java-simple"
                branch "master"
            }
        }
        branches {
            notifications(NotifyOnNewBranchesType.USE_PLANS_NOTIFICATION_SETTINGS) // DOESN'T WORK
            branch(name: 'feature_ui_improvements') {
                vcsBranchName 'feature/ui_improvements'
                notifications(NotifyOnNewBranchesType.USE_PLANS_NOTIFICATION_SETTINGS) // WORKS
            }

        }
    }
}
```

I'll try to fix this problem next and keep you up-to-date.

Best regards,
Michael

**Comment by sohrab-** [comment]
Thanks for providing the work-around.

**Comment by mrueegg** [comment]
Hi,

We've just released a new version including a bug fix for this. Please update your plug-in installation.

Thanks again for reporting it!

Best regards,
Michael
