### ISSUE TITLE
Feature Proposal - Set naming versions for deployment releases

### ISSUE THREAD

**Issue by tom999** [mibexsoftware/bamboo-plan-dsl-plugin#8]
For deployment projects you can set the naming pattern for versioning.
We overwrite it with the maven version like "${bamboo.shortPlanName}-${bamboo.maven.version}".
Haven't found it in the DSL api to set this.

Bamboo Help for "Naming versions for deployment releases"
https://confluence.atlassian.com/bamboo0511/naming-versions-for-deployment-releases-827359178.html

**Comment by mrueegg** [comment]
Implemented with version 1.4.0. Thanks for reporting this!
