### ISSUE TITLE
[secrets] how to manage secrets variables

### ISSUE THREAD

**Issue by ozbillwang** [mibexsoftware/bamboo-plan-dsl-plugin#83]
This plugin looks very promise and far better than the new feature [bamboo spec](https://docs.atlassian.com/bamboo-specs-docs/6.5.0/) in bamboo server. I do have feeling that Bamboo developer team just clone your idea directly. 

But with variables management, I can't find any suggestions to handle secret variable in this plugin. 

How can I do that?

**Comment by mrueegg** [comment]
@ozbillwang Thanks for your nice words about our plug-in. Could you please explain what you mean by "secret variables"? Do you mean accessing Bamboo variables (like described here: https://github.com/mibexsoftware/bamboo-plan-dsl-plugin/wiki/Advanced-topics#accessing-bamboos-env-variables)?

**Comment by ozbillwang** [comment]
In our origination, we have no permission to create global variables in bamboo. Second, we have thousands projects and plans.  It is not convenience to create global variables. 

Then I have to create variables for each plan, because bamboo doesn't support variables at project level. 

when use this plugin, I hope to set variables in a new plan, especially for  secrets (password_xxxx). How to do that?

**Comment by ozbillwang** [comment]
got your point. Thanks.
