### ISSUE TITLE
Plan is always disabled

### ISSUE THREAD

**Issue by tom999** [mibexsoftware/bamboo-plan-dsl-plugin#87]
We have 2 Plans in 1 Stage and one of the Plan is always disabled by the Bamboo DSL, even it is set to be enabled.

            stage("building") {
                description("Builds Api")
                manual(false)

                job("JOB1", "Build") {
                    enabled(true)
                    description("build api")
                    tasks {
                        checkout() {
                            description 'Checkout Default Repository'
                            forceCleanBuild true
                            repository(projectName) {

                            }
                        }

Thanx for any help in this issue

Attached:
- Code for the pipeline
- log form DSL Plugin while creating pipeline

[DslApiConfig.groovy.txt](https://github.com/mibexsoftware/bamboo-plan-dsl-plugin/files/2348824/DslApiConfig.groovy.txt)
[employees.log](https://github.com/mibexsoftware/bamboo-plan-dsl-plugin/files/2348827/employees.log)

**Comment by mrueegg** [comment]
Hi,

Please excuse my late response.

I have problems to reproduce this. Could you please explain what you mean by "2 plans in one stage"? Would it be possible for you to give me a minimal example of a DSL where this problem occurs?

Thanks,
Michael

**Comment by tom999** [comment]
In a nutshell it's like the dsl attached, but with this DSL it works :-(

But I don't see, where we make something wrong in our mor complex code. Is there a good way to find it out (meaning of debugging)?
[DisableProblem.groovy.txt](https://github.com/mibexsoftware/bamboo-plan-dsl-plugin/files/2369603/DisableProblem.groovy.txt)

**Comment by mrueegg** [comment]
Hi @tom999 

Please excuse my late response.

You are right, with `DisableProblem.groovy.txt` I wasn't able to reproduce this. And for the real case in `DslApiConfig.groovy.txt` I'm missing some files that are referenced in it to be able to reproduce it. When I look at it, I also cannot see something suspicious.

Have you tried to enable "verbose logging" in the task settings to see if this yields something in the log that can help us?

Best regards,
Michael

**Comment by tom999** [comment]
In the subclass "miscellaneous" we had another enabled method call.
But "miscellaneous" has no enabled an therefore it went to class job and disabled our plan.
Problem solved!
Thanx Michael for your super support!
