### ISSUE TITLE
Document the recommended Build set up

### ISSUE THREAD

**Issue by alanraison** [mibexsoftware/bamboo-plan-dsl-plugin#89]
I'm trying to convert my build plans from bamboo-specs to plandsl but I am a little confused about the recommended set up. Should there be a separate PlanDSL build, or can the seed task be embedded in the main "code" build? In either case, when a VCS change triggers a build, will there be a race condition where the build configuration is updated whilst a "code" build is running?

**Comment by mrueegg** [comment]
@alanraison We actually recommend to have the DSL scripts in a separate build only containing the seed task, therefore having it separate from the actual builds. 

Are you referring to race conditions that could happen when both the seed plan and referenced other plans are running concurrently? If yes, we haven't experienced any. When a build plan is triggered, any changes to its plan that occur during the build shouldn't affect it.

**Comment by alanraison** [comment]
Yes, I mean if you make a code change that also affects the build plan, will the seed project update the build plan before the build plan runs? I suppose I could set up a could of linked repositories with different include/exclude patterns and make the build plan a child build of the seed project build.

Thanks for your help!
