### ISSUE TITLE
Plan variables are not accessible to the Plan DSL seed task

### ISSUE THREAD

**Issue by krbcmt** [mibexsoftware/bamboo-plan-dsl-plugin#99]
Is it possible to set variables in the Seed task Plan that can get accessed by `System.getenv("bamboo_some_var)"`? As far as I can tell, the only environment variables available to the Seed task are JVM system properties. Is this improvement possible or am I missing the right way to access those variables?

**Comment by mrueegg** [comment]
Hi,

You can access Bamboo build variables within your DSL scripts (see https://github.com/mibexsoftware/bamboo-plan-dsl-plugin/wiki/Advanced-topics#accessing-bamboos-env-variables). Does that help you or are you looking for something else?

Best regards,
Michael

**Comment by krbcmt** [comment]
That is exactly what I was looking for. I guess I'm one of _those_ persons. Thank you for the response and sorry for the trouble.
